# Generated by Django 4.1.1 on 2022-09-21 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('second_name', models.CharField(max_length=50)),
                ('born_date', models.DateField(verbose_name='date_of_birth')),
            ],
        ),
        migrations.CreateModel(
            name='Saga',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('summary', models.TextField(max_length=5000)),
                ('isSaga', models.BooleanField(default=False)),
                ('sagaSequence', models.PositiveSmallIntegerField(null=True)),
                ('authors', models.ManyToManyField(to='library_app.author')),
                ('saga', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='library_app.saga')),
            ],
        ),
    ]
